### ISSUE TITLE
Storing Sessions

### ISSUE THREAD

**Issue by thedevale** [setiawanhu/laravel-madeline-proto#1]
Hi, how are sessions stored?
Can I run multiple telegram accounts?

Thanks

**Comment by setiawanhu** [comment]
Hi!

> Hi, how are sessions stored?

The sessions are stored into a file which contains the serialized `danog\MadelineProto\API` instance.

> Can I run multiple telegram accounts?

Based on this [issue](https://github.com/danog/MadelineProto/issues/187) you can run multiple telegram accounts by defining different instance with different session file name.

For now, the current wrapper that I made only supporting only 1 telegram session out of the box by defining the session file name at `session_file` property from `telegram.php` config file.

But there's a workaround for that. You still can create multiple session instances by doing this following code:
```php
//YourController.php
use danog\MadelineProto\API;
use Hu\MadelineProto\MadelineProto;
use Hu\MadelineProto\ClientMessages;

//...

public function doSomethingWithTelegram() {
   //instantiating new session instance
   $session = new API('your_session_file_path.madeline', config('telegram.settings'));
   
   //then pass the session instance to the wrapper for doing authentication business logic
   $madeline = new MadelineProto($session);

   //or pass the instance's 'messages' property to the messages wrapper for doing some messaging business logic
   //(note: the session must have been authenticated)
   $messaging = new ClientMessages($session->messages);

   //...
}
```

Hope this helps
