### ISSUE TITLE
get People NearBy

### ISSUE THREAD

**Issue by frech87** [setiawanhu/laravel-madeline-proto#13]
Hi. It is great job. But I can not use getLocated
`$inputGeoPoint = ['_' => 'inputGeoPoint', 'lat' => 40.2514, 'long' => 49.5020, 'accuracy_radius' => 42];
        $location = MadelineProto::getClient()->contacts->getLocated(['background'=> false, 'geo_point' => $inputGeoPoint, 'self_expires' => 0]);
        ddd($location);`
It return this answer 

`array:7 [▼
  "_" => "updates"
  "updates" => []
  "users" => []
  "chats" => []
  "date" => 1610980851
  "seq" => 0
  "request" => array:12 [▼
    "apifactory" => true
    "datacenter" => 2
    "_" => "contacts.getLocated"
    "type" => "Updates"
    "contentRelated" => true
    "promise" => Amp\Deferred {#1642 ▶}
    "method" => true
    "unencrypted" => false
    "body" => array:3 [▶]
    "serialized_body" => b"D¼HÓ\x01\x00\x00\x00É¬·óq\eà- D@ÇK7‰AÀH@\x00\x00\x00\x00" (ERROR: invalid input)
    "sent" => 1610980851
    "tries" => 0
  ]
]`

**Comment by setiawanhu** [comment]
Hello! Thank you for the feedback!

My apologies, I think that's not error caused by the `laravel-madeline-proto` package. It's more like caused by the `MadelineProto` itself.

Please refer to the [documentations](https://github.com/danog/MadelineProtoDocs) for tracing your issue.
Thanks!
