### ISSUE TITLE
Cannot send message (ClientMessages constructor issue)

### ISSUE THREAD

**Issue by AbuTabikh** [setiawanhu/laravel-madeline-proto#14]
Great work however when I faced this issue

**Argument 1 passed to Hu\MadelineProto\ClientMessages::__construct() must implement interface danog\MadelineProto\messages, instance of danog\MadelineProto\APIFactory given, called in \vendor\setiawanhu\laravel-madeline-proto\src\MadelineProto.php on line 150**
 
My Controller 
`<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use  Hu\MadelineProto\TelegramObject;
use  Hu\MadelineProto\Facades\Messages;

class TestController extends Controller
{
   
    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index(){

        $payload = new TelegramObject();
        $payload->peer = '@user-name';
        $payload->message = 'Your Message';
        Messages::sendMessage($payload);
    }

}
`

**Comment by grfbr** [comment]
Hi @AbuTabikh 

I tried here and I had the same issue. I try few modifications but no luck;

@setiawanhu could you give some support? 

Thanks :)

**Comment by setiawanhu** [comment]
Hi @AbuTabikh and @grfbr !

Thank you for your feedback! I apologize for the long wait.

Hmmm... I found the method that causing the error. Somehow the method returns different instance (previously i'm quite sure it returns `danog\MadelineProto\messages` instance, but now it returns `danog\MadelineProto\APIFactory` instead).

I could offer 2 solutions:
1. Upgrade the version to `1.2.2` which I will publish in PR #16 
2. Use the `MadelineProto::getClient()` insead using the `Messages` facade and using the original method provided by the MadelineProto 

    **P.S**: the original method does not support TelegramObject as the argument, you may need to call `toArray()` method to make it work)

Maybe this example for the second solution may help you guys out:
```php
use Hu\MadelineProto\Facades\MadelineProto;

//...

/**
 * Show the application dashboard.
 *
 * @return \Illuminate\Contracts\Support\Renderable
 */
public function index(){

    $payload = new TelegramObject();
    $payload->peer = '@user-name';
    $payload->message = 'Your Message';

    MadelineProto::getClient()->messages->sendMessage($payload->toArray());;
}
```
