### ISSUE TITLE
Conflict telegram.php config file

### ISSUE THREAD

**Issue by sghadery** [setiawanhu/laravel-madeline-proto#17]
Hi,
i use a [telegram-bot-sdk](https://irazasyed.github.io/telegram-bot-sdk/) library in our project.
this library publish telegram.php file in app/config and this conflict with your vendor:publish command. how can i solve that?

**Comment by setiawanhu** [comment]
Hi @sghadery!

I think there will be no issue with it, just combine the config arrays from the `telegram-bot-sdk` library and the `laravel-madeline-proto` one.

after the combining, the `telegram.php` file should be look like this:
```php
// config/telegram.php

return [
    'telegram-bot-sdk-key' => [
        'other-telegram-bot-sdk-key' => 'value'
    ],
    'sessions' => [ // laravel-madeline-proto's
        // ...
    ],
    'settings' => [ // laravel-madeline-proto's
        // ...
    ],
];
```
