### ISSUE TITLE
session of type string

### ISSUE THREAD

**Issue by abron-devs** [setiawanhu/laravel-madeline-proto#18]
hi

after login with multi account try used

$account = Account::first();

$telegramSession = $account->telegramSession;

$madelineProto = $this->factory->get($telegramSession);

dd($madelineProto);

![image](https://user-images.githubusercontent.com/78970113/125962709-bd939005-6d13-44f8-ac16-c2788dc9882d.png)

![image](https://user-images.githubusercontent.com/78970113/125963669-596461bd-e2ea-4a84-8237-e59dd4ac9ccd.png)

 please help me

**Comment by setiawanhu** [comment]
Hi @abron-devs!

I don't think that you can pass the Madeline Proto object as an argument for `dd()` method. AFAIK, it is because the object is not _arrayable_ like the Laravel's objects does. So it's not a bug from either Laravel / the laravel-madeline-proto package.

**Comment by abron-devs** [comment]
how can i use multi session ?
i not found wiki used multi session for call madelineProto methods

**Comment by setiawanhu** [comment]
Hello @abron-devs! 
Sorry for the wait.

You can read information about multi sessions from this [wiki](https://github.com/setiawanhu/laravel-madeline-proto/wiki/Multiple-Telegram-Account). Hope this helps.
