### ISSUE TITLE
Laravel installation error

### ISSUE THREAD

**Issue by sauravkumal** [setiawanhu/laravel-madeline-proto#5]
I get the following error while running 'composer require setiawanhu/laravel-madeline-proto' in my laravel project v7.0. Is there something i am missing? Cannot find any relevant info in the web.

Using version ^1.0 for setiawanhu/laravel-madeline-proto
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for paragonie/random_compat (locked at v9.99.99) -> satisfiable by paragonie/random_compat[v9.99.99].
    - setiawanhu/laravel-madeline-proto 1.0.0 requires danog/madelineproto ^5.1 -> satisfiable by danog/madelineproto[5.1.0, 5.1.1, 5.1.10, 5.1.11, 5.1.12, 5.1.13, 5.1.14, 5.1.15, 5.1.17, 5.1.18, 5.1.19, 5.1.2, 5.1.20, 5.1.21, 5.1.22, 5.1.23, 5.1.24, 5.1.25, 5.1.26, 5.1.27, 5.1.28, 5.1.29, 5.1.3, 5.1.30, 5.1.31, 5.1.32, 5.1.33, 5.1.34, 5.1.4, 5.1.5, 5.1.6, 5.1.7, 5.1.8, 5.1.9].
    - setiawanhu/laravel-madeline-proto 1.0.1 requires danog/madelineproto ^5.1 -> satisfiable by danog/madelineproto[5.1.0, 5.1.1, 5.1.10, 5.1.11, 5.1.12, 5.1.13, 5.1.14, 5.1.15, 5.1.17, 5.1.18, 5.1.19, 5.1.2, 5.1.20, 5.1.21, 5.1.22, 5.1.23, 5.1.24, 5.1.25, 5.1.26, 5.1.27, 5.1.28, 5.1.29, 5.1.3, 5.1.30, 5.1.31, 5.1.32, 5.1.33, 5.1.34, 5.1.4, 5.1.5, 5.1.6, 5.1.7, 5.1.8, 5.1.9].
    - setiawanhu/laravel-madeline-proto 1.0.2 requires danog/madelineproto ^5.1 -> satisfiable by danog/madelineproto[5.1.0, 5.1.1, 5.1.10, 5.1.11, 5.1.12, 5.1.13, 5.1.14, 5.1.15, 5.1.17, 5.1.18, 5.1.19, 5.1.2, 5.1.20, 5.1.21, 5.1.22, 5.1.23, 5.1.24, 5.1.25, 5.1.26, 5.1.27, 5.1.28, 5.1.29, 5.1.3, 5.1.30, 5.1.31, 5.1.32, 5.1.33, 5.1.34, 5.1.4, 5.1.5, 5.1.6, 5.1.7, 5.1.8, 5.1.9].
    - danog/madelineproto 5.1.0 requires danog/tgseclib ^3 -> satisfiable by danog/tgseclib[3].
    - danog/madelineproto 5.1.1 requires danog/tgseclib ^3 -> satisfiable by danog/tgseclib[3].
    - danog/madelineproto 5.1.10 requires danog/tgseclib ^3 -> satisfiable by danog/tgseclib[3].
    - danog/madelineproto 5.1.11 requires danog/tgseclib ^3 -> satisfiable by danog/tgseclib[3].
    - danog/madelineproto 5.1.12 requires danog/tgseclib ^3 -> satisfiable by danog/tgseclib[3].
    - danog/madelineproto 5.1.13 requires danog/tgseclib ^3 -> satisfiable by danog/tgseclib[3].
    - danog/madelineproto 5.1.14 requires danog/tgseclib ^3 -> satisfiable by danog/tgseclib[3].
    - danog/madelineproto 5.1.15 requires danog/tgseclib ^3 -> satisfiable by danog/tgseclib[3].
    - danog/madelineproto 5.1.17 requires danog/tgseclib ^3 -> satisfiable by danog/tgseclib[3].
    - danog/madelineproto 5.1.18 requires danog/tgseclib ^3 -> satisfiable by danog/tgseclib[3].
    - danog/madelineproto 5.1.19 requires danog/tgseclib ^3 -> satisfiable by danog/tgseclib[3].
    - danog/madelineproto 5.1.2 requires danog/tgseclib ^3 -> satisfiable by danog/tgseclib[3].
    - danog/madelineproto 5.1.20 requires danog/tgseclib ^3 -> satisfiable by danog/tgseclib[3].
    - danog/madelineproto 5.1.21 requires danog/tgseclib ^3 -> satisfiable by danog/tgseclib[3].
    - danog/madelineproto 5.1.22 requires danog/tgseclib ^3 -> satisfiable by danog/tgseclib[3].
    - danog/madelineproto 5.1.23 requires danog/tgseclib ^3 -> satisfiable by danog/tgseclib[3].
    - danog/madelineproto 5.1.24 requires danog/tgseclib ^3 -> satisfiable by danog/tgseclib[3].
    - danog/madelineproto 5.1.25 requires danog/tgseclib ^3 -> satisfiable by danog/tgseclib[3].
    - danog/madelineproto 5.1.26 requires danog/tgseclib ^3 -> satisfiable by danog/tgseclib[3].
    - danog/madelineproto 5.1.27 requires danog/tgseclib ^3 -> satisfiable by danog/tgseclib[3].
    - danog/madelineproto 5.1.28 requires danog/tgseclib ^3 -> satisfiable by danog/tgseclib[3].
    - danog/madelineproto 5.1.29 requires danog/tgseclib ^3 -> satisfiable by danog/tgseclib[3].
    - danog/madelineproto 5.1.3 requires danog/tgseclib ^3 -> satisfiable by danog/tgseclib[3].
    - danog/madelineproto 5.1.30 requires danog/tgseclib ^3 -> satisfiable by danog/tgseclib[3].
    - danog/madelineproto 5.1.31 requires danog/tgseclib ^3 -> satisfiable by danog/tgseclib[3].
    - danog/madelineproto 5.1.32 requires danog/tgseclib ^3 -> satisfiable by danog/tgseclib[3].
    - danog/madelineproto 5.1.33 requires danog/tgseclib ^3 -> satisfiable by danog/tgseclib[3].
    - danog/madelineproto 5.1.34 requires danog/tgseclib ^3 -> satisfiable by danog/tgseclib[3].
    - danog/madelineproto 5.1.4 requires danog/tgseclib ^3 -> satisfiable by danog/tgseclib[3].
    - danog/madelineproto 5.1.5 requires danog/tgseclib ^3 -> satisfiable by danog/tgseclib[3].
    - danog/madelineproto 5.1.6 requires danog/tgseclib ^3 -> satisfiable by danog/tgseclib[3].
    - danog/madelineproto 5.1.7 requires danog/tgseclib ^3 -> satisfiable by danog/tgseclib[3].
    - danog/madelineproto 5.1.8 requires danog/tgseclib ^3 -> satisfiable by danog/tgseclib[3].
    - danog/madelineproto 5.1.9 requires danog/tgseclib ^3 -> satisfiable by danog/tgseclib[3].
    - Conclusion: don't install setiawanhu/laravel-madeline-proto 1.0.3|install danog/tgseclib 3
    - Conclusion: don't install danog/tgseclib 3
    - Installation request for setiawanhu/laravel-madeline-proto ^1.0 -> satisfiable by setiawanhu/laravel-madeline-proto[1.0.0, 1.0.1, 1.0.2, 1.0.3].

**Comment by setiawanhu** [comment]
Hi thanks for the feedback!

I'm not sure about this issue either. It's probably a version conflict happened in the danog/madelineproto dependencies. Someone have been asked the [same issue](https://github.com/danog/MadelineProto/issues/745) before. 
It's working when you manually adding the dependency to your `composer.json` file.

```diff
require: {
    ...
+   "setiawanhu/laravel-madeline-proto": "^1.0"
}
```
and then run the `composer update` command.

**Comment by sauravkumal** [comment]
Ok thanks a lot. Manually adding the dependency solved this issue for me.

**Comment by Cloud-Dark** [comment]
> 

then how to update version to 1..3.0?
